### ISSUE TITLE
The tmax mentioned in the caption of the figure may be wrong

### ISSUE THREAD

**Issue by mbaudin47** [martinkrz/posepi1#1]
I enabled the "figure captions" button and read the caption:

![image](https://github.com/user-attachments/assets/2b8708c8-4a49-4df5-9ff5-0453ac506562)

The text is "_the time at which peak infected fraction occurs tmax = 163.0 days (dotted orange line)_". But this seems to be wrong, because the true `tmax` (as presented in the upper right panel) is 49.9.

It seems to me that the bug is at:

https://github.com/martinkrz/posepi1/blob/0cbdd886374563d92f92659307ef76f5833a4d86/R/1.plot.R#L31

where the variable `tmax` is used instead of `timax`. This is the name correctly used at:

https://github.com/martinkrz/posepi1/blob/0cbdd886374563d92f92659307ef76f5833a4d86/R/1.text.R#L26

The confusion stems from the fact that tmax is the maximum of the time interval used for simulation. I guess that using the variable name `timax` may be a confusing variable. Perhaps `t_infection_maximum` would be a better variable name.

Anyway, thank you for this great app!

**Comment by martinkrz** [comment]
Thanks for reporting this. You're right, the figure caption uses 'tmax' value but should be using 'timax' value. 

I've fixed this in v1.0.5 and updated our shiny server.

**Comment by mbaudin47** [comment]
Thank you very much! This works perfectly now.
