### ISSUE TITLE
The coefficient beta printed in the top right panel might be wrong

### ISSUE THREAD

**Issue by mbaudin47** [martinkrz/posepi1#2]
I enabled the "interpretive text" checkbutton in the left and this prints a table in the top right panel.

![image](https://github.com/user-attachments/assets/63f553b5-5bbc-4e81-aa4a-47d41100bebb)

I think that the value of beta printed in the "SIR model parameters" is wrong. Compare with [^Bjørnstad2020], figure 1 page 455. We read R0 = 3, 1/gamma = 14 and beta = 0.21 (in the legend).

![image](https://github.com/user-attachments/assets/bad4d051-8e2d-4b27-b6ed-78bb8b237177)

The app prints β = 0.0238 /day while the paper prints β = 0.21 /day. It seems to me that the paper is correct, because R0 = beta / gamma = 0.21 * 14 = 2.94 which is very close to 3. If instead we use beta = 0.0238 as in the R/Shiny app, we get R0 = 0.0238 * 14 = 0.33, which is way too low.

I think that the bug is here:

https://github.com/martinkrz/posepi1/blob/0cbdd886374563d92f92659307ef76f5833a4d86/R/1.text.R#L6

The equation is not `beta  = gamma / R0`. It is `beta  = gamma * R0`. In this case, we get beta = (1 / 14) * 3 = 0.2143, which is consistent with the paper.

[^Bjørnstad2020]: Bjørnstad, O. N., Shea, K., Krzywinski, M., & Altman, N. (2020). Modeling infectious epidemics. _Nature methods_, _17_(5), 455-457.

**Comment by martinkrz** [comment]
Thanks for reporting this. 

Beta value display is fixed in v1.0.6

**Comment by mbaudin47** [comment]
Thank you very much for the fast bugfix Indeed, it works now:

![image](https://github.com/user-attachments/assets/60d35c29-bc4a-4285-93ce-23ab3fb33338)
